<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>

<body>
<b><?=$msg?></b>
<h1>Form</h1>

<form method="post">

    Username: <input type="text" name="username" value="<?=$form->username?>"> <br>
    Email <input type="email" name="email" value="<?=$form->email?>"><br>

    Message:
    <textarea name="message" placeholder="Type a message..."><?=$form->message?></textarea>
    
    
    <button>Submit</button>
</form>




</body>

</html>